/** Shared domain entry points for the Lambda adapters (REST + remote MCP).
 * Reuses src/mcp/commands.ts so the remote API uses exactly the same operation
 * vocabulary and calculation path as the browser session. No state is kept
 * between calls — `evaluate` returns the post-operation project for chaining. */
import type {Project} from '../../src/domain/project.js';
import {validateProject} from '../../src/domain/validation.js';
import {createProject} from '../../src/data/defaults.js';
import {evaluateOnProject,MODEL_NOTES} from '../../src/mcp/commands.js';
import type {EditArgs,EvalJob} from '../../src/mcp/commands.js';
import {buildLayout} from '../../src/template/layout.js';
import {buildAreas} from '../../src/template/faces.js';
import {simulate} from '../../src/model/simulation.js';
import {simulateDaily} from '../../src/model/dailySimulation.js';
import {describeModel} from '../../src/model/modelInfo.js';
import {APP_VERSION} from '../../src/data/defaults.js';

/** Accepts a caller-supplied project JSON or falls back to the shipped default. */
export function resolveProject(input:unknown):Project{
 if(input===undefined||input===null)return createProject();
 validateProject(input);
 return input;
}

/** Runs the same two-stage simulation the browser worker performs, synchronously. */
async function runSimulation(p:Project,opts:{daily:boolean}):Promise<EvalJob>{
 const thermal=simulate(p);
 if(!opts.daily)return{thermal,daily:null,dailyThermal:null,dailyMilkStatus:'complete'};
 const out=simulateDaily(p);
 return{thermal,daily:out.daily,dailyThermal:out.thermal,dailyMilkStatus:out.status==='error'?'error':'complete'};
}

export interface EvaluateInput{project?:unknown;scenarioId?:string;operations?:EditArgs[];includeDaily?:boolean}

/** Stateless equivalent of the browser `evaluate` tool. Ops are applied exactly
 * once on an internal clone, so ids generated by add_device/duplicate_device in
 * `operations[].applied` match the returned `project` for chaining. */
export function evaluateProject(args:EvaluateInput){
 return evaluateOnProject(resolveProject(args.project),{
  operations:args.operations??[],
  scenarioId:args.scenarioId,
  includeDaily:args.includeDaily,
 },runSimulation);
}

export function describe(project?:unknown){
 return{model:describeModel(resolveProject(project)),modelNotes:MODEL_NOTES};
}

/** get_default_project payload: the shipped default project plus the IDs an
 * agent needs to address operations (probes, areas, scenario/device ids). */
export function defaultProject(){
 const p=createProject(),l=buildLayout(p.template);
 return{
  project:p,
  appVersion:APP_VERSION,
  scenarios:p.scenarios.map(s=>({id:s.id,name:s.name,readOnly:s.readOnly,fanIds:s.fans.map(f=>f.id),systemIds:s.waterSystems.map(w=>w.id),nozzleIds:s.waterSystems.flatMap(w=>w.nozzles.map(n=>n.id))})),
  probes:l.probes.map(q=>({id:q.id,label:q.label,kind:q.kind})),
  areas:buildAreas(l).map(a=>({id:a.id,label:a.label,probeIds:a.probeIds})),
  note:'projectをevaluateへそのまま渡せる。schemaVersion必須',
  modelNotes:MODEL_NOTES,
 };
}
