import {icon} from './dom.js';
export function layout(){return `
<header class="app-header"><div class="brand"><span class="brand-mark">${icon('barn',27)}</span><div><strong>Cooling Planner</strong><span>モデル牛舎で、暑熱対策を試す</span></div><span class="version">v0.9</span></div><div class="header-actions"><span id="status" role="status" data-state="calculating">計算準備中</span><button data-action="evidence" class="quiet">${icon('info',16)}根拠と仮定</button><button data-action="load" class="quiet">読込</button><button data-action="save" class="primary">${icon('save',16)} 案を保存</button></div></header>
<div id="error-banner" role="alert" hidden><span id="error-message"></span><button data-action="dismiss-error" aria-label="エラーを閉じる">×</button></div>
<section class="environment-bar" aria-label="共通の気象条件"><div class="model-badge">${icon('barn',24)}<div><strong>フリーストール / 50床</strong><small id="dimensions-label">36.4 × 23.5 m · 70評価点</small></div></div><div id="environment-fields"></div><span class="weather-note">全案共通の外気条件<br>地点別は60分・日乳量は固定気象の24時間反復</span></section>
<main class="workspace">
<aside class="equipment-panel panel"><div class="panel-heading"><span class="eyebrow">01 / EQUIPMENT</span><h2>対策を選ぶ・配置する</h2></div><div id="equipment-controls"></div><div class="inspector"><h3>選択中の設備</h3><div id="device-selector"></div><div id="device-properties"></div></div></aside>
<section class="simulation-area" aria-label="牛舎の操作">
 <div class="stage panel"><div class="stage-toolbar"><div id="scenario-tabs" class="segments"></div><div class="segments modes"><button data-mode="3d">標準3D</button><button data-render="realistic">リアル3D</button><button data-mode="2d">2D</button></div></div>
 <div class="stage-subhead"><div class="metric-tabs"><button data-metric="deficit">放熱不足</button><button data-metric="delta">放熱改善</button><button data-metric="speed">風速</button><button data-metric="temperature">気温</button></div><span>色は60分平均・全案共通目盛り</span></div>
 <div class="scene-wrap"><div id="scene"></div><div class="scene-top-left"><span class="scene-label">操作できるモデル牛舎</span><strong id="scene-selection">採食7</strong></div><div class="camera-buttons"><button data-camera="overview" title="全体を見る">全体</button><button data-camera="top">上面</button><button data-camera="side">側面</button></div><div class="scene-bottom-left"><span class="mouse-hint">設備をドラッグして移動<br>背景で回転 / ホイールで拡大</span></div><div id="scene-live" class="scene-live"></div><div id="realistic-note" class="realistic-note" hidden>風・水滴は作用の模式表現 · 時刻で運転状態を切替</div><div id="scene-busy" class="scene-busy" hidden>変更した条件で再計算中…</div></div>
 <div class="stage-footer"><div id="legend"></div><div class="scene-switches"><label><input id="show-roof" type="checkbox" data-view="roof">屋根断面</label><label><input id="show-flow" type="checkbox" data-view="flow">風</label><label><input id="show-particles" type="checkbox" data-view="particles">散水</label><label id="heatmap-switch" hidden><input id="show-heatmap" type="checkbox" data-view="heatmap">ヒートマップ</label><label><input id="show-analysis" type="checkbox" data-view="analysis">分析表示</label></div></div>
 <div class="edit-toolbar"><div><button data-action="undo" id="undo-button">↶ 戻す</button><button data-action="redo" id="redo-button">↷ やり直す</button></div><span id="edit-hint">選択 → 移動・高さ・向き → 結果を比較</span><button data-action="copy-scenario" id="copy-scenario">別案へコピー</button><button data-action="reset-active" id="reset-active">基準に戻す</button></div>
 </div>
 <div class="timeline-panel panel"><div class="timeline-heading"><div><span class="eyebrow">02 / TIME</span><h2>散水と放熱の変化 <small>選択地点・0〜60分</small></h2></div><div class="chart-tabs"><button data-chart="qW" class="active">放熱量</button><button data-chart="temperatureC">気温</button><button data-chart="filmKg">保持水</button></div></div><div id="timeline-chart"></div><div class="transport"><button data-action="play" id="play-button">${icon('play',15)} 再生</button><input id="time-slider" type="range" min="0" max="3600" step="1" value="0" aria-label="表示時刻"><output id="time-display">00:00</output><select id="play-speed" aria-label="再生倍率"><option value="60">60倍</option><option value="120" selected>120倍</option><option value="300">300倍</option></select></div><p class="micro">カードと色は60分平均。再生は計算済みの時系列を表示します。乳量・受胎の時間予測ではありません。</p></div>
 <div class="comparison-panel panel"><div class="timeline-heading"><div><span class="eyebrow">03 / COMPARE</span><h2>同じ条件で、案を比較</h2></div><button data-action="export-results" class="quiet small">結果JSON</button></div><div id="comparison"></div></div>
 <div class="area-panel panel"><div class="timeline-heading"><div><span class="eyebrow">04 / AREAS</span><h2>エリア別の平均 <small>代表点の単純平均</small></h2></div></div><div id="area-summary"></div></div>
</section>
<aside class="results-panel panel"><div class="panel-heading"><span class="eyebrow">RESULT / 60 MIN AVERAGE</span><h2>この場所の変化</h2><label class="sr-only" for="probe-select">比較する地点</label><select id="probe-select"></select></div><div id="results"></div></aside>
</main>
<footer class="footer"><span>ブラウザ内で計算 · ログイン・外部送信なし</span><span>現地検証ではなく、根拠と仮定を使うモデル比較</span><button data-action="settings">共通設定・保存</button></footer>
<dialog id="evidence-dialog"><div class="dialog-head"><h2>モデルの根拠と仮定</h2><button data-close="evidence-dialog" aria-label="閉じる">×</button></div><div id="evidence-body"></div></dialog>
<dialog id="settings-dialog"><div class="dialog-head"><h2>共通設定・保存</h2><button data-close="settings-dialog" aria-label="閉じる">×</button></div><div id="settings-body"></div></dialog>
<dialog id="reference-dialog"><div class="dialog-head"><h2>乳量・受胎の参照条件</h2><button data-close="reference-dialog" aria-label="閉じる">×</button></div><div id="reference-body"></div></dialog>
<input id="file-input" type="file" accept=".json,application/json" hidden><div id="toast" role="status" hidden></div>`}
